### ISSUE TITLE
db.collection.name - reconsider only capturing the first collection name

### ISSUE THREAD

**Issue by gregkalapos** [open-telemetry/semantic-conventions#1132]
From the DB stabilisation working group.

Currently the DB SemConv for [`db.collection.name`](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md#common-attributes) states that: 

> The collection name MAY be parsed from the query text, in which case it SHOULD be the first collection name found in the query.

It came up in the Elasticsearch PR that there are very good reasons to store all collection names and storing the first one would be confusing: https://github.com/open-telemetry/semantic-conventions/pull/1002#issuecomment-2150436821

Although other database systems may be different, we discussed this in the WG and a few things came up:
- This decision opens questions, we anticipate that users often will ask why only the first one is captured? Currently this can't be answered by looking at the spec
- Even in the WG we were not able to recall why this was the decision 

Notes from meeting:

- Ordering - is a,b,c the same as c,b,a
  - Alphabetical
  - As present in the query
- Cardinality
- Format (csv?)
  - db.collection.names
- It’s part of the span name (back to format)
- For metrics, make query text as opt-in

Goal of the issue: re-iterate this decision
- [ ] Try to come up with a solution that does not raise above questions and potentially stored all collection names. 
- [ ] If we stick to this decision at least try to document why and make sure the spec has good reasoning for this, plus it should also enable to store all collection names in specific db spec (see Elasticsearch:  https://github.com/open-telemetry/semantic-conventions/pull/1002)

**Comment by trask** [comment]
Discussed in DB semconv meeting last week.

We could give flexibility to database-specific semconv in case of multiple collections:

* `db.collection.name` MAY be the primary collection (for some instrumentation-specific definition of primary collection)
* `db.collection.name` MAY be the first collection (when there isn't a clear / easy definition of primary collection)
* `db.collection.name` MAY be a comma-separated value (note potential downside of user and backend confusion since the `db.collection.name` name is singular and implies it is a single collection name)
* Span name MAY include all collection names (allowing `db.collection.name` to be a single collection)

We also considered not capturing `db.collection.name` in cases where there are multiple, but we think that will lead to more user confusion / questions about why that attribute is empty.

As far as user confusion / questions about why only the first collection name is captured, Java has been capturing the first collection name for quite a while without causing any related user questions.

**Comment by trask** [comment]
> * `db.collection.name` MAY be a comma-separated value (note potential downside of user and backend confusion since the db.collection.name name is singular and implies it is a single collection name)

this is the only one that has a notable downside I think

@gregkalapos @swallez do you think that including all of the collection names in the span name is enough, or do you think the additional benefit of putting multiple values into `db.collection.name` for elasticsearch is worth the potential user and backend confusion?

**Comment by swallez** [comment]
From my perspective, keeping a single string is enough. As I said in https://github.com/open-telemetry/semantic-conventions/pull/1002#issuecomment-2150436821: when multiple names are provided, they're just an "anonymous alias" for a series of indices that all have the same structure. From a query engine perspective they form a single source.

**Comment by gregkalapos** [comment]
@trask do you mean we'd use the comma separated list in the span name, but not in `db.collection.name`? I think from a user's perspective it's ok - but from the spec point of view it'd be a bit tricky to handle: right now we have the `action + target` format, where target is one of the attributes - in this case we'd deviate from that, right?

But based on what @swallez says, one could maybe even argue that ultimately the comma separated list is a single collection name, which in this case is a pattern that matches multiple indices. I'm not super confident about this argument, but maybe it's worth exploring.

**Comment by trask** [comment]
Discussed in DB semconv meeting this week:

* It's ok for elasticsearch (and others DB vendor specific semconv) to capture comma-separated list of collections when the operation applies equally to all of the collections (e.g. searching with exact same criteria across multiple collections).
* We re-affirmed https://github.com/open-telemetry/semantic-conventions/issues/1132#issuecomment-2179091654.
