### ISSUE TITLE
Resource attributes for network addresses of a host

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/semantic-conventions#131]
The Elastic Common Schema defines the semantic conventions [`host.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-ip) and [`host.mac`](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-mac), that state, respectively, the known IP and MAC addresses of a given host.

This issue tracks incorporating them into the OpenTelemetry semantic conventions. There are two open questions or clarifications that I feel need to be resolved before adding these to OpenTelemetry:
1. Should IPv4 and IPv6 be distinguished in separate semantic conventions?
2. Should this belong to the `host` namespace of is this a network semantic convention that should be under the `system.network` namespace?

These may be part of https://github.com/open-telemetry/opentelemetry-specification/issues/3556 if approved.

**Comment by ChrsMark** [comment]
Hey @mx-psi! 

Regarding the distinction of IPv4 and IPV6 I like the idea of being more specific.

About the second question: From infrastructure perspective I would consider `host.ip` and `host.mac` as attributes of a given host. So I would say that we could follow [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-host.html) in that part without an issue.

Another thing that we might consider here related to the second question is if it would make sense to report system metrics under the `host.*` namespace as well. So instead of `system.cpu.utilization` we use sth like `host.cpu.utilization`. This was covered by ECS at https://github.com/elastic/ecs/pull/2129.
On this we will need to also take into account how we will report metrics from other entities like containers and VMs. We would need to make the topology distinction clear so as to not mix things.

**Comment by mx-psi** [comment]
Filed #203 for the IPv4 and IPv6 addresses case.

**Comment by mx-psi** [comment]
Closing this since we now have `host.ip` and `host.mac`
