### ISSUE TITLE
General thread attributes - Java's `Thread.currentThread().getId()` is deprecated

### ISSUE THREAD

**Issue by arminru** [open-telemetry/semantic-conventions#1375]
`Thread.currentThread().getId()` is deprecated since java 19. There is a `Thread.currentThread().threadId()` instead.

_Originally posted by @johantiden in https://github.com/open-telemetry/opentelemetry-specification/pull/789#discussion_r1736010637_

---

This would need to be updated in https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/attributes.md#general-thread-attributes.

**Comment by johantiden** [comment]
To reiterate:
`Thread.currentThread().getId()` has been deprecated in favor of `Thread.currentThread().threadId()`, which is more secure since it can't be overridden.
https://bugs.openjdk.org/browse/JDK-8017617?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

We should change the example docs to reflect the latest Java LTS version.
