### ISSUE TITLE
Remove `system.device` attribute in favor of `device.id`

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/semantic-conventions#1432]
### Area(s)

area:system

### Is your change request related to a problem? Please describe.

 It looks like `system.device` and `device.id` are duplicated attributes: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/device.md

### Describe the solution you'd like

Single attribute to reference the same object: `device.id` looks more descriptive 

### Additional context

https://github.com/open-telemetry/semantic-conventions/pull/1408#discussion_r1770627540

**Comment by mx-psi** [comment]
Discussed on the 2024-12-12 System Semconv WG meeting, @braydonk to take a look and close this since we already made a decision on this.

**Comment by braydonk** [comment]
While it is not super clear, The `device` namespace appears to be particularly about a mobile device based on the description of the `device.id` attribute and the other attributes on the namespace. (Arguably something should be done to clarify that it is meant in particular for mobile devices) 

After speaking as a group I think we agree as a group that `system.device` is distinct enough since it is about a device as an OS concept that is presumably part of a system represented by a `host` entity.
