### ISSUE TITLE
Normalizing HTTP header names is ambiguous

### ISSUE THREAD

**Issue by Flarna** [open-telemetry/semantic-conventions#304]
[HTTP Span SemConv](https://github.com/open-telemetry/semantic-conventions/blob/v1.21.0/docs/http/http-spans.md#http-request-and-response-headers) requires to normalize HTTP header name attributes.

using lower case is fine because HTTP tells to handle header names case insensitive (HTTP/2 requires to them even lowercase).

But replacing `-` by `_` seems problematic because both chars are allowed in http header names.

Therefore this may result in merging/overwrite issues on instrumentation side and unclear interpretation on backend side.

**Comment by Oberon00** [comment]
Probably we should define which one wins in this case. I'd go for the hyphen one, as the underscore one does not usually occur and could be used by a bad actor to confuse tracing.

**Comment by Flarna** [comment]
I would be in favor of removing this part of the normalization but I fear that ship has sailed or would at least requires a 2.0 release.

**Comment by trask** [comment]
> I would be in favor of removing this part of the normalization but I fear that ship has sailed or would at least requires a 2.0 release.

It's not too late yet, but soon will be. We will be marking HTTP semantic conventions as stable very soon.

Removing the `-` to `_` part of the normalization seems reasonable to me, and reporting attributes like:

* `http.request.header.content-type=["application/json"]`
* `http.request.header.x-forwarded-for=["1.2.3.4", "1.2.3.5"]`

instead of

* `http.request.header.content_type=["application/json"]`
* `http.request.header.x_forwarded_for=["1.2.3.4", "1.2.3.5"]`

@open-telemetry/specs-semconv-approvers do we have a reason to try to avoid dashes (`-`) in attribute names?

I don't see discussion/context of why we would want to do this particular part of the normalization when it was originally proposed in https://github.com/open-telemetry/opentelemetry-specification/pull/1898#issuecomment-914238509

**Comment by trask** [comment]
sent #369 to help attract attention and force a decision one way or another on this issue before stabilization
