### ISSUE TITLE
Introduce `process.cpu.count` or `process.cpu.logical.count` metric?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#313]
*[We're interested in this from the JVM perspective since we are looking to stabilize `jvm.cpu.count`, and want to see if we should be considering `jvm.cpu.logical.count` instead.]*

**Pros for `process.cpu.logical.count`:**
* consistency with `system.cpu.logical.count`

**Pros for `process.cpu.count`:**
* I don't think processes have a concept of physical cores(?), and so a single `count` metric may be all that's needed

**Comment by jonatan-ivanov** [comment]
Based on these:
[`system.cpu.physical.count`](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/system-metrics.md#metric-systemcpuphysicalcount):
>Reports the number of actual physical processor cores on the hardware

[`system.cpu.logical.count`](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/system-metrics.md#metric-systemcpulogicalcount):
>Reports the number of logical (virtual) processor cores created by the operating system to manage multitasking

If I understand these correctly, if I buy a CPU, open it up and count the cores (or read what's on the box :D), I should get the `system.cpu.physical.count`, e.g.: 16.
But because of technologies like Hyper-Threading, the OS will see more cores, let's say twice as much, e.g.:32, as well as the JVM (or other processes).

In this context, I think `process.cpu.physical.count` does not make much sense to me since processes (running in an OS) will only see the "logical" cores not the "physical" ones. I think `process.cpu.count` is ok sine it is implicitly "logical", I would only go with `process.cpu.logical.count` if everything else is consistent with `system` and this one should be too.

(Note: this number can be less than `system.cpu.logical.count` and can go up or down because of cgroups.)

**Comment by trask** [comment]
Closing, discussed in Java SIG and consensus aligns with @jonatan-ivanov's comment above
