### ISSUE TITLE
Mark exceptions.* conventions stable

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/semantic-conventions#365]
The `RecordException` API has been included in the stable releases of at least two languages, .NET and Java. In both of these languages, the API sets exception attributes as part of its stable offering, despite the fact that the semantic conventions for exceptions are still labeled as experimental. We should consider marking the conventions as stable, and if we do so, we should also mark the corresponding attributes under logs as stable.

https://github.com/open-telemetry/semantic-conventions/blob/main/docs/exceptions/exceptions-logs.md
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/exceptions/exceptions-spans.md

**Comment by arielvalentin** [comment]
_Although my following comments are more related to the SDK than Semconv, I have some thoughts and issues I am facing with how SDK collects and reports exceptions._

I am keen on the spec reviewer to reconsider the structure of exceptions as well as considering changing the SDK spec to defer parsing/interpreting/formatting the exception until it is exported.

Some of the challenges I face with this in Ruby is that the choice of using `Exception#full_message` does not allow us to structure the exception for custom exporters without having to _parse_ or sanitize the backtrace. 

In order for us to this _today_ we have to parse the `exception.backtrace` and reconstruct the exception object and then we would be able to report it using the SDK.  

Changing the SDK Events to retain a reference to the exception object, would allow end users to create custom exporters like that could report exceptions using the Sentry SDK, which requires an `Exception` object type[^1] without having to parse the backtrace. 

Thanks!

[^1]: https://www.rubydoc.info/gems/sentry-ruby/Sentry#capture_exception-class_method

**Comment by cijothomas** [comment]
@arielvalentin I do not think spec is prohibiting any language implementations from storing the full exception itself on Span/SpanEvent/LogRecord! 
Here's Java's PR for adding to SpanEvent : https://github.com/open-telemetry/opentelemetry-java/pull/4162
.NET had similar discussions, but not implemented for SpanEvents. But it stores the full exception in LogRecord.

**Comment by arielvalentin** [comment]
The API at least seems to indicate it must be recorded as an event.

> This is a specialized variant of [AddEvent](https://opentelemetry.io/docs/specs/otel/trace/api/#add-events), so for anything not specified here, the same requirements as for AddEvent apply.

https://opentelemetry.io/docs/specs/otel/trace/api/#record-exception

> An exception SHOULD be recorded as an Event on the span during which it occurred. The name of the event MUST be "exception".

https://opentelemetry.io/docs/specs/otel/trace/exceptions/#recording-an-exception

Since none of this is prescribed that it _must_ happen in the implementation of Record Exception then we are free to hold a reference to the exception? 

The Event API does not specify a means of adding data so in this case the Java SDK uses a sub class to extend the functionality of the Event type and overrides the Attributes getter to lazily memoize the semconv version of the attributes. 

In cases where I would write a custom exporter then I would have to cast the EventData object to a ExceptionEventData in order to gain access to the original exception. 🤔 

Am I reading that right?

cc: @open-telemetry/ruby-maintainers thoughts?

**Comment by lmolkova** [comment]
Stabilized in #619 !
