### ISSUE TITLE
Should HTTP `server.address` and `server.port` prioritize `Host` header over virtual host name?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#388]
Since one of the motivations for these attributes on the server side:

* `server.address`
* `server.port`
* `url.path`
* `url.query`
* `url.scheme`

is to reconstruct the original URL, does it make sense to prioritize capturing `server.address` and `server.port` from the `Host` header instead of the current state of prioritizing the virtual host name?

(and since we have more clarity on these being logical attributes now, and since we can introduce more lower-level attributes to capture virtual host name / port in the future as needed)

here's the current definition of `server.address` (as captured on the server side):

https://github.com/open-telemetry/semantic-conventions/blob/b127e121b9b458e83a0fee8a32f7eb6721912951/model/http-common.yaml#L70-L80

**Comment by Oberon00** [comment]
IMHO: No, they should not. Unfortunately, the host header often contains bogus content, and it can be captured separately in http.request.header.host.

**Comment by lmolkova** [comment]
Agree with @Oberon00. Reverse proxies don't always preserve the original host header (and custom configuration can put anything there). 

In my mental model, since the "primary server name" is essentially user-configurable, this is the way for users to force `server.address` to be something they want.

Something we should probably do:
- change "The primary server name of the matched virtual host" to something like "Explicit user configuration (if provided) or a primary server name"
- add "Original host used by the client such as `host` component of [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header, [X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) or similar" to come 3rd before `Host` header

WDYT?

**Comment by Oberon00** [comment]
One thing that just occured to me: server.address is also used as metric attribute for HTTP server metric. A bad Host header could easily cause a cardinality explosion there. So that is a no-go also for that reason I believe. https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/http-metrics/#metric-httpserverduration

**Comment by trask** [comment]
> A bad Host header could easily cause a cardinality explosion there.

this discussion led me to a similar worry, let me know if you think #401 is sufficient

**Comment by trask** [comment]
> Explicit user configuration (if provided) or a primary server name

are you thinking instrumentation configuration? do we need to mention that? or is this important enough to include something like "instrumentation SHOULD provide configuration"

**Comment by trask** [comment]
Closing this issue, I think the original question has been answered, and there are follow-up issues and PRs for the other discussion items:

* #408
* #414
* #401
