### ISSUE TITLE
Consider renaming process.runtime.jvm.* metrics to process.runtime.java.*

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/semantic-conventions#40]
Stems from discussion in the 5/17 java SIG about potential limitations of alternative implementations of the metrics for graalVM and android runtimes. 

The namespace "jvm" clearly refers to the java virtual machine. Android and graalVM runtimes are not the same as the java virtual machine, yet where possible they would want to emulate the jvm runtime metric conventions. GraalVM in particular is taking steps to implement JMX APIs currently used in the JVM runtime to implement the conventions.

"jvm" seems like an appropriate namespace at first glance because several languages besides java run on the JVM (groovy, scala, kotlin, etc) and all produce the same metrics. 

So we have the java language, which can run on different runtimes (jvm, android, graalVM). And we have the jvm runtime, on which multiple languages run. What do all these things have in common? Arguably, that they're all part of the broader **java ecosystem**.

The "java" namespace in "process.runtime.java.*" would not refer to the java language, but the broader java ecosystem. By using this definition, we could have android and graalVM implementations of the metrics.

**Comment by arminru** [comment]
Are there any metrics currently defined for the JVM which would not apply to the other runtimes in the Java ecosystem, or vice versa?

At first glance, they all look generic enough to apply to all of them, particularly since attributes like `pool` allow for any value and not just "G1 Eden Space" and such, but there might be Graal-specific metrics or attributes one would like to add which don't apply to the JVM in return.

**Comment by trask** [comment]
From JVM runtime metrics WG

* `java` is most commonly used to refer to the language
* `jvm` is the runtime

What to do with GraalVM/Substrate and Android? (TornadoVM?)

* `process.runtime.jvm.threads.count` generally applies

Suspect that GraalVM will be able to emit many of the JVM metrics in our stable set.

Are there any GraalVM or Android metrics that do not apply to JVM?

* classes initialized at build-time vs runtime (maybe not the best example of metric since doesn't change over time)

where would we put those? can this be figured out later? yes
