### ISSUE TITLE
Produce documentation that outlines http changes from 1.20.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/semantic-conventions#43]
I was trying to understand what changes in http conventions and it is not easy to do since it seems the changes happened across more than one PR. One way to get his info is to use git history or git blame, but that's time consuming and error prone and also because we moved the repo I can't be sure I am comparing to the correct baseline (the 1.20.0 is in the spec repo).

It would be great if we could produce a side-by-side comparison of semconv 1.20.0 and \<next version\>.

**Comment by tigrannajaryan** [comment]
This is a great way to represent it. Thanks @arminru

**Comment by lmolkova** [comment]
Thanks a lot @arminru ! It looks great!

**Comment by Oberon00** [comment]
@arminru Just looking a bit at the list you compiled, and have some notes:

* New attribute `server.name`: This does not exist. In the linked PR https://github.com/open-telemetry/opentelemetry-specification/pull/3402 it seems to have been mistakenly used in the CHANGELOG only. I just created #126 to fix the CHANGELOG copy in this repository.
* Consequently, net.host.name will be server.address in most cases. While very unlikely in the context of http, it may theoretically also be client.address. This is the case for all net.host/peer attributes (incl net.sock.host/peer) (they may be set as part of the general span conventions even when not described in the http conventions).

**Comment by arminru** [comment]
Thanks for double-checking, @Oberon00. I updated the comment above.

**Comment by trask** [comment]
(added this as a blocker for HTTP semconv stability to make sure it gets done since this will be important for both instrumenters and users who are upgrading their instrumentation to a version that implements the stable HTTP semconv)

**Comment by trask** [comment]
Summary of changes to HTTP semantic conventions since version `v1.20.0`.

## Common attributes across HTTP client and HTTP server spans:

* `http.method` -> `http.request.method` (and only capture "known" methods, otherwise `_OTHER`)
* `http.status_code` -> `http.response.status_code`
* `http.request_content_length` -> `http.request.body.size` (open discussion at #456)
* `http.response_content_length` -> `http.response.body.size` (open discussion at #456)
* `http.request.header.<key>` -> Removed dashes to underscores normalization in `<key>`
* `http.response.header.<key>` -> Removed dashes to underscores normalization in `<key>`
* `user_agent.original` (No change)
  * Note: see below if updating from version `v1.18.0` or earlier
* `net.protocol.name` (Recommended if not `http`) -> `network.protocol.name` (Opt-In)
* `net.protocol.version` -> `network.protocol.version` (and examples fixed: `2.0` -> `2` and `3.0` -> `3`)
  * Note: see below if updating from version `v1.19.0` or earlier
* `net.sock.family` -> Removed
* `net.sock.peer.addr` -> `network.peer.address`
* `net.sock.peer.name` -> Removed
* `net.sock.peer.port` -> `network.peer.port` (and capture even if same as `net.peer.port`)
* New: `http.request.method_original`
* New: `network.transport` (Opt-In)
* New: `error.type`

## HTTP client span attributes:

* `http.url` -> `url.full`
* `http.resend_count` -> `http.request.resend_count`
* `net.peer.name` -> `server.address` (open discussion at #457)
* `net.peer.port` -> `server.port` (open discussion at #457)

## HTTP server span attributes:

* `http.route` (No change)
* `http.target` -> split into `url.path` and `url.query`
* `http.scheme` -> `url.scheme` (and factor in X-Forwarded-Scheme, Forwarded headers)
* `http.client_ip` -> `client.address`
* `net.host.name` -> `server.address` (and base only on Host, X-Forwarded-Host, Forwarded headers)
* `net.host.port` -> `server.port` (and base only on Host, X-Forwarded-Host, Forwarded headers)

## HTTP client and server span names:

The `{http.method}` portion of span names is replace by `HTTP` when `{http.method}` is `_OTHER`.

Note: see below if updating from version `v1.17.0` or earlier.

## HTTP client duration metric

* Name: `http.client.duration` -> `http.client.request.duration`
* Unit: `ms` -> `s`
* Description: `Measures the duration of inbound HTTP requests.` -> `Duration of HTTP server requests.`
* Histogram buckets: boundaries updated to reflect change from milliseconds to seconds, and zero bucket boundary removed
* Attribute changes:
  * `http.method` -> `http.request.method` (and only capture "known" methods, otherwise `_OTHER`)
  * `http.status_code` -> `http.response.status_code`
  * `net.peer.name` -> `server.address` (open discussion at #457)
  * `net.peer.port` -> `server.port` (open discussion at #457)
  * `net.sock.peer.addr` -> Removed
  * `net.protocol.name` (Recommended if not `http`) -> `network.protocol.name` (Opt-In)
  * `net.protocol.version` -> `network.protocol.version` (and examples fixed: `2.0` -> `2` and `3.0` -> `3`)
    * Note: see below if updating from version `v1.19.0` or earlier
  * New: `error.type`
  * New: `url.scheme` (open discussion at #450)

## HTTP server duration metric

* Name `http.server.duration` -> `http.server.request.duration`
* Unit: `ms` -> `s`
* Description: `Measures the duration of inbound HTTP requests.` -> `Duration of HTTP server requests.`
* Histogram buckets: boundaries updated to reflect change from milliseconds to seconds, and zero bucket boundary removed
* Attribute changes:
  * `http.route` (No change)
  * `http.method` -> `http.request.method` (and only capture "known" methods, otherwise `_OTHER`)
  * `http.status_code` -> `http.response.status_code`
  * `http.scheme` -> `url.scheme` (and factor in X-Forwarded-Scheme, Forwarded headers)
  * `net.protocol.name` (Recommended if not `http`) -> `network.protocol.name` (Opt-In)
  * `net.protocol.version` -> `network.protocol.version` (and examples fixed: `2.0` -> `2` and `3.0` -> `3`)
    * Note: see below if updating from version `v1.19.0` or earlier
  * `net.host.name` (Recommended) -> `server.address` (Opt-In, and base only on Host, X-Forwarded-Host, Forwarded headers)
  * `net.host.port` (Recommended) -> `server.port` (Opt-In, and base only on Host, X-Forwarded-Host, Forwarded headers)
  * New: `error.type`


## If you are coming from an earlier semantic convention version:

### If updating from version `v1.19.0` or earlier:

* `http.flavor` -> `network.protocol.version` (`2.0` and `3.0` -> `2` and `3`)

### If updating from version `v1.18.0` or earlier:

* `http.user_agent` -> `user_agent.original`

### If updating from version `v1.17.0` or earlier:

#### HTTP server span name:

* when `http.route` is available
  * `{http.route}` -> `{summary} {http.route}`
* when `http.route` is not available
  * `HTTP {http.method}` -> `{summary}`

where `{summary}` is `{http.method}`, unless `{http.method}` is `_OTHER`,
in which case `{summary}` is `HTTP`.

#### HTTP client span name:

* `HTTP {http.method}` -> `{summary}`

where `{summary}` is `{http.method}`, unless `{http.method}` is `_OTHER`,
in which case `{summary}` is `HTTP`.

**Comment by tigrannajaryan** [comment]
Thank you @trask for the summary.

**Comment by trask** [comment]
Closed by https://opentelemetry.io/blog/2023/http-conventions-declared-stable/
