### ISSUE TITLE
[HTTP server] Should `:authority` be higher on the list than `Host`?

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/semantic-conventions#451]
The current spec says:

> HTTP server instrumentations SHOULD do the best effort when populating `server.address` and `server.port` attributes and SHOULD determine them by using the first of the following that applies:
>
> * The original host which may be passed by the reverse proxy in the [`Forwarded#host`][Forwarded], [`X-Forwarded-Host`][X-Forwarded-Host], or a similar header.
> * The [`Host`][Host header] header.
> * The [`:authority`][HTTP/2 authority] pseudo-header in case of HTTP/2 or HTTP/3

However, [the RFC](https://datatracker.ietf.org/doc/html/rfc9113#section-8.3.1) says something different:
> The ":authority" pseudo-header field conveys the authority portion ([Section 3.2](https://www.rfc-editor.org/rfc/rfc3986#section-3.2) of [[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986)]) of the target URI ([Section 7.1](https://www.rfc-editor.org/rfc/rfc9110#section-7.1) of [[HTTP](https://datatracker.ietf.org/doc/html/rfc9110)]). The recipient of an HTTP/2 request MUST NOT use the Host header field to determine the target URI if ":authority" is present.

To me it sounds that when an HTTP 2.0 server receives an incoming request, the `:authority` header has higher priority than `Host`.

**Comment by lmolkova** [comment]
I put it after `Host` because from RFC9113 perspective, they should be the same and the order does not matter.

[A server SHOULD treat a request as malformed if it contains a Host header field that identifies an entity that differs from the entity in the ":authority" pseudo-header field.](https://datatracker.ietf.org/doc/rfc9113/#section-8.3.1:~:text=A%20server%0A%20%20%20%20%20%20SHOULD%20treat%20a%20request%20as%20malformed%20if%20it%20contains%20a%20Host%20header%0A%20%20%20%20%20%20field%20that%20identifies%20an%20entity%20that%20differs%20from%20the%20entity%20in%0A%20%20%20%20%20%20the%20%22%3Aauthority%22%20pseudo%2Dheader%20field.)
