### ISSUE TITLE
Are `http.(request|response).body.size` worth being recommended on HTTP spans (vs opt-in)?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#456]
While these can be useful, they are not as generally useful as the other recommended attributes on HTTP spans.

And [`http.(client|server).(request|response).body.size`](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpserverrequestbodysize) metrics (and exemplars) seem to cover some of their usefulness.

As we think about telemetry cost, I think it's worth asking if these are worth being recommended vs opt-in.

**Comment by lmolkova** [comment]
Opt_in for them makes sense to me.

At the same time, as a user, I can opt-in to `content-length` header. 
We tell that body size is not always the same as content length (not known with chunked encoding), but we never tell how to measure it otherwise.
Also, considering the difference between time-to-first vs time-to-last-byte body size attributes have an ambiguity: do they represent content-length or the actual number of bytes read?

Given all these concerns, I'd prefer to make attributes opt_in and keep them experimental or remove them completely.

**Comment by trask** [comment]
> Given all these concerns, I'd prefer to make attributes opt_in and keep them experimental or remove them completely.

Probably the easiest thing at this point is to remove them completely. I'll send a PR.
