### ISSUE TITLE
Create semconv-messaging-approvers team

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#529]
Since there is already a Messaging WG that meets regularly, it would be great to have a github team and related CODEOWNERS updates to involve them in issues and PRs (e.g. #528)

@pyohannes does this make sense to you, and if so could you provide list of people to add?

**Comment by pyohannes** [comment]
Great, let's start out with those people:

@lmolkova @carlosalberto @joaopgrassi @dpauls @pyohannes

Anybody in the list who doesn't want to be added, please let us know.

Also, any other volunteers are very welcome :slightly_smiling_face:.

**Comment by trask** [comment]
@open-telemetry/specs-semconv-maintainers can you open a community issue, and we can get someone from @open-telemetry/technical-committee to create the group?

**Comment by joaopgrassi** [comment]
Do we need a community issue? In the past TC members created the group from an issue in the semconv repo, like https://github.com/open-telemetry/semantic-conventions/issues/343. 

@kamalaboulhosn are you already part of the OTel org? You are welcome to join the group and look at PRs, join the meetings but to be added to the group in GitHub, you need to be part of the OTel org.

If not yet, please take a look at the guidelines in the community repo: https://github.com/open-telemetry/community/blob/main/community-membership.md#member

**Comment by tigrannajaryan** [comment]
Team created: https://github.com/orgs/open-telemetry/teams/semconv-messaging-approvers/members

**Comment by kamalaboulhosn** [comment]
@joaopgrassi I am not, no. I am trying to figure out how to be involved in discussions and decisions that will affect messaging-based products like Google Pub/Sub. There has been some new discussion on these conventions that don't exactly match what we were already planning to do and are deep into the implementation on for our Open Telemetry. Given experience in debugging a wide variety of customer issues that could be helped by telemetry, figured there was an opportunity to help. Looks like the goal is to have Open Telemetry experts rather than people who are necessarily experts in the domain in which the tracing is occurring, though. I probably can't be much help in terms of general Open Telemetry contributions. We can perhaps just proceed with our plan as originally intended and if then refine later if there are some helpful conventions that are established.

**Comment by joaopgrassi** [comment]
Hi @kamalaboulhosn 

> Looks like the goal is to have Open Telemetry experts rather than people who are necessarily experts in the domain in which the tracing is occurring,

That is absolutely not the case! We do 100% want experts in messaging systems such as yourself to help us validate that what we have designed works and makes sense. So your experience is much needed/wanted!

We have a SIG (special interest group) that meets every Thursday at 8:00 PT. You can find the calendar/zoom link in the community repo [Semantic Conventions: Messaging](https://github.com/open-telemetry/community#specification-sigs). You can also find our slack channel there. Feel free to drop by. 

It would be great if you could join the meetings and share your needs/thoughts on what doesn't match. I'm sure we can learn a lot from you and hopefully arrive at a solution that works for everyone. Once you join the meeting/collaborate, you can apply to the OTel org but you don't need that to get started :). 

CC @pyohannes
