### ISSUE TITLE
Add namespaces to JVM metric attributes?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#61]
Replaces https://github.com/open-telemetry/opentelemetry-specification/issues/3417

There are (currently) three proposals being discussed for metric attribute namespaces in #51.

This purpose of this issue is to try to arrive at consensus for future JVM metric attribute renames based on each of these three proposals.

## Today:

* `process.runtime.jvm.memory.*`
  * `type`
  * `pool`
* `process.runtime.jvm.gc.duration`
  * `gc`
  * `action`
* `process.runtime.jvm.threads.count`
  * `daemon`
* `process.runtime.jvm.buffer`
  * `pool`

## Option A: No namespaces required

Possibly no change.

Maybe `gc` -> `name` to align with Option C.

## Option B: Explicit namespaces required

PR already exists for this: https://github.com/open-telemetry/semantic-conventions/pull/20

* `process.runtime.jvm.memory.*`
  * `type` -> `memory.type`
  * `pool` -> `memory.pool.name`
* `process.runtime.jvm.gc.duration`
  * `gc` -> `gc.name`
  * `action` -> `gc.action`
* `process.runtime.jvm.threads.count`
  * `daemon` -> `thread.daemon`
* `process.runtime.jvm.buffer`
  * `pool` -> `buffer.pool.name`

## Option C: Namespace inherited from metric namespace

* `process.runtime.jvm.memory.*`
  * `type` (implicitly `process.runtime.jvm.memory.type`)
  * `pool` (implicitly `process.runtime.jvm.memory.pool`)
* `process.runtime.jvm.gc.duration`
  * `gc` -> `name` (implicitly `process.runtime.jvm.gc.name`)
  * `action` (implicitly `process.runtime.jvm.gc.action`)
* `process.runtime.jvm.threads.count`
  * `daemon` (implicitly `process.runtime.jvm.threads.daemon`)
* `process.runtime.jvm.buffer`
  * `pool` (implicitly `process.runtime.jvm.buffer.pool`)

**Comment by jack-berg** [comment]
This [TC vote has concluded](https://github.com/open-telemetry/semantic-conventions/issues/51#issuecomment-1604775862) and we should be able to proceed with resolving this issue.

I'm in favor of option c because I view it as the least risky. There's no opportunity for future conventions to disagree with the semantics we define for general `memory.type` / `memory.pool.name` / `gc.name` / `gc.action`, since all attribute names will be clearly scoped to JVM. If general semantic conventions emerge that match JVM semantics, we can adopt those and change the name of the attributes via [telemetry schemas](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/schemas/README.md).

**Comment by jack-berg** [comment]
I need to clarify my previous comment. I prefer the names of option c, but with fully qualified names rather than relying on any inheritance from the metric name's namespace:

* `process.runtime.jvm.memory.*`
  * `process.runtime.jvm.memory.type`
  * `process.runtime.jvm.memory.pool`
* `process.runtime.jvm.gc.duration`
  * `process.runtime.jvm.gc.name`
  * `process.runtime.jvm.gc.action`
* `process.runtime.jvm.threads.count`
  * `process.runtime.jvm.threads.daemon`
* `process.runtime.jvm.buffer`
  * `process.runtime.jvm.buffer.pool`

I also like option b, but don't want to get blocked on a discussion on whether the java memory, gc, thread, and buffer concepts are language agnostic.
