### ISSUE TITLE
Attributes registry - Move messaging-system specific attributes to their own section

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/semantic-conventions#640]
~In the traces messaging convention we have a [table with the attributes](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/messaging/messaging-spans.md#messaging-attributes) which should be the "general" attributes, shared by all messaging systems.~

~But in #634 new attributes for `gcp` are being added and those are showing up together with the general attributes.~

~We should refactor things, so these message-system specific attributes are split in their own pages. Similar to what is done for the [Database semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md)~

In the [attributes registry page for messaging](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/messaging.md#messaging-attributes) system-specific messaging attributes are mixed together with "general" attributes. It would be better if they were separated into their own section in the page.

**Comment by joaopgrassi** [comment]
Will triage and assign to someone from the messaging wg when we are ready to work on this.

**Comment by pyohannes** [comment]
This doesn't apply to [attributes in messaging semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/messaging/messaging-spans.md#messaging-attributes), because there system-specific attributes are already split out in separate files.

This applies to the [attribute registry](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/messaging.md#messaging-attributes), where currently all messaging attributes are mixed together in one table.

**Comment by joaopgrassi** [comment]
Ah you  are right, I somehow thought that the new gcp attributes were being rendered in the "general" attributes table, my mistake. Renamed this to reflect the correct facts. thanks!
