### ISSUE TITLE
Clarify semantics of system.cpu.time and system.cpu.utilization

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/semantic-conventions#647]
We have [system.cpu.time and system.cpu.utilization](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md#systemcpu---processor-metrics) semantic conventions which don't explain what the metrics track.

Is `system.cpu.time` just the cumulative value of `system.cpu.utilization` or there are other differences? If they track the exact same value with same attributes and the only difference is that one is cumulative and the other is delta do we really need both?

**Comment by ChrsMark** [comment]
@open-telemetry/semconv-system-approvers is this still valid?
I guess the current description of the [system.cpu.utilization description](https://github.com/open-telemetry/semantic-conventions/blob/v1.26.0/docs/system/system-metrics.md?plain=1#L142) is valid and accurate.

The only missing piece is about making it `opt-in` since it can be calculated from the `system.cpu.time` metric.
Otherwise, we can close this issue.

**Comment by ChrsMark** [comment]
Filed https://github.com/open-telemetry/semantic-conventions/issues/1130 for further discussion on the requirement level.
Will close this current issue in a couple of days if there is no objection until then, since the original [question](https://github.com/open-telemetry/semantic-conventions/issues/647#issue-2088785072) should be covered now.

/cc @open-telemetry/specs-semconv-approvers @open-telemetry/specs-semconv-maintainers
