### ISSUE TITLE
Add system uptime metric

### ISSUE THREAD

**Issue by andrzej-stencel** [open-telemetry/semantic-conventions#648]
**What are you trying to achieve?**

I want to add a metric to the semantic conventions that will describe the system uptime. How about `system.uptime`?

**Additional context.**

This is reported by Telegraf as `uptime` field of the `system` metric (in seconds).

Here's a related proposal on the `hostmetrics` receiver to add this metric: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14130.

**Comment by minuk-dev** [comment]
Q. Is there any plan to do it?

**Comment by mx-psi** [comment]
@kernelpanic77 offered to do it here https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31627#issuecomment-2133882411 :)

**Comment by dmitryax** [comment]
Looks like we have an agreement here. Just need someone to submit a PR

**Comment by tigrannajaryan** [comment]
Is there any way we can generalize this to be an "uptime" of any entity, not just of "system"? What if we make this an `uptime` metric with the Resource describing what it is about (e.g. Resource can have "host.name=foo" to indicate that it is an uptime of a host).

**Comment by andrzej-stencel** [comment]
> Is there any way we can generalize this to be an "uptime" of any entity, not just of "system"? What if we make this an `uptime` metric with the Resource describing what it is about (e.g. Resource can have "host.name=foo" to indicate that it is an uptime of a host).

I suppose we could do it, I wonder what others think.

The `uptime` attribute name would not be namespaced, unlike `system.uptime` that is namespaced to `system`. Looking at the [Attributes Registry](https://github.com/open-telemetry/semantic-conventions/blob/v1.27.0/docs/attributes-registry/README.md), it doesn't look like we currently have any non-namespaced attributes in the semantic conventions. Is that true?

**Comment by rogercoll** [comment]
> Is there any way we can generalize this to be an "uptime" of any entity, not just of "system"?

I think this is part of a broader discussion taking place in https://github.com/open-telemetry/semantic-conventions/issues/1161 (`system.uptime` vs `process.uptime` vs `container.uptime`). The main benefit of using the metric without namespace seems to be dashboards correlation and avoiding deduplication. But it comes at the cost of implying resource attributes to corresponding metrics (not sure if this is possible in semconv), for example, the `uptime` metric should always be linked to either `host.name`, `process.pid` or `container.id`. 

During the System Semantic Conventions SIG (20/06/2024) [we agreed on keeping the metrics](https://github.com/open-telemetry/semantic-conventions/issues/1161#issuecomment-2181532608) in namespaces (even if there are duplications) due to:

> The potential for minute differences between the meanings of seemingly identical metrics between the different contexts
    The namespaces also semantically represent the reporting source, making query scenarios more clear (i.e. "I want all my operating system process metrics" or "I want all my jvm metrics" has a clear separation due to the metrics reported from each source all having their respective namespaces)
