### ISSUE TITLE
DB Convention does not cover batch/multi/envelope operations

### ISSUE THREAD

**Issue by ndimiduk** [open-telemetry/semantic-conventions#712]
Our API has a small alphabet of relatively simple operations key-value operations (`get`, `put`, `delete`, &c.) For these, the operation names seem clear. We also have a set of operations that support bulk/batching of operations. these can be homogeneous or heterogeneous. For example, `batch` can accept a set of any combination of `get`, `put`, `delete`, &c. We also support a generic system for server-side compare-and-mutate, where some predicate based on a query over existing data is provided, and when the predicate returns true, some operation is applied — that operation can be a simple or a batch operation. for these collections of heterogenous operations, how should be annotate the span?

**Comment by lmolkova** [comment]
Assuming there is just one bulk operation that deals with batch as a whole, I can think of the following solutions:

E.g bulk operation consists of `["get foo", "delete bar"]`. 

**Option 1. Attributes with array values**
   - `db.operation = bulk`
   - `db.mydb.sub_operations = [get, delete]`,  and `db.mydb.some_other_attribute= [foo, bar]` ...

Cons: 
  - bulk operations are common and we should consider defining sub-operation attributes in top `db` namespace
  - the relationship between elements in attribute arrays is based on index (if we record more than one attribute per sub-operation) which is subtle and error prone
  - bulk operations with a lot of sub-operations might be too long for some backends that have low limits on the attribute length

**Option 2.  Events/logs**
   - `db.operation = bulk`
   - Plus I emit an event for each sub-operation that contains grouped attributes describing that operation

We do something similar in messaging (with links though):
- if a batch of messages is sent, send operation should have links to all messages being sent and their unique per-message properties should be on the link. 
- if there is just one message its properties should be recorded either on the link or on the span. 

DB operations don't have an individual trace-context, so links are not suitable here, but events could work. Then it should also be easier to enable/disable sub-operation reporting depending on the needs. the drawback is that events/logs could go to a different backend

Cons:
- if we don't have a case for multiple attributes describing one operation, this seems like an overkill and Option 1 would be a better choice.
 
Option 3. Creating artificial spans per sub-operation 

Cons:
 - misleading
 - costly (both perf and volume)

**Additional things to consider:**

- we should have an attribute that records the size of a batch (in case of messaging it's called `messaging.batch.message_count`)
- metrics: 
  - we should consider having a metric that measures number of sub-operations (since  `db.operation.duration` would not  provide a count for bulk operations)
  - bulk duration could be a different metric (e.g. with different histogram boundaries)

**Comment by jcocchi** [comment]
Cosmos DB is currently creating a string attribute `db.cosmosdb.batch_operations` with each operation type in the batch and the count for that type. Adding an attribute to the convention would be useful to standardize this. 

We should be able to capture:
- Overall count for batch
- Operations in batch
- Optionally: more information for each batch operation according to each db's requirements (count, status code etc.)

I prefer the simplicity of Option 1. Attributes with array values, but agree it creates a challenge for additional information about each batch operation. The most important piece of additional information for Cosmos DB is operation count, so maybe something like the following could work: `db.batch.count = 6` `db.mydb.sub_operations = [get:2, delete:4]` . Capturing information beyond operation count may be too clunky in this format though

**Comment by roji** [comment]
@lmolkova isn't that conflating "batch" with "bulk", by proposing `db.operation = bulk` for something containing two things (get and delete)? The standard naming for this seems to be batching, where a bulk command usually corresponds to a command that changes multiple records (like a SQL UPDATE statement).

Regardless, the commands contained in a batch are typically the same in every aspect as a standalone command not executed in a batch; each command has a SQL (so `db.statement`), a `db.operation` (select, insert...), a set of parameters (something not currently represented in the semantic conventions, but which could/should), and any other attributes which a specific database may add. For me this strongly points towards represents the batched commands as spans, which would allow querying/interpreting them just like commands which aren't batched. Introducing a new way to represent batched commands may seem simpler on first look, but actually creates two ways to represent the same logical thing, and makes the data more difficult to interpret. In effect, a batch is conceptually is just a container for commands.

Note that it's true that certain attributes must be the same across all commands in the batch, e.g. the hostname, network info, etc. So these attributes could optionally be lifted up to the span representing the batch, leaving on the command only attributes which can vary (e.g. SQL, parameter info).

**Comment by jcocchi** [comment]
@roji one difference between batch operations and standalone operations is the duration. If you add each operation in a batch as its own span, is the duration of each sub operation the same as the parent? Is it 0? This could also create confusion because it may make those operations appear either abnormally quick or abnormally long

**Comment by roji** [comment]
@jcocchi that's true indeed... I don't know if there are other OTel cases where a larger "logical container" span wrap nested spans as in this case, and how that's best represented...
