### ISSUE TITLE
DB sanitization uniform format

### ISSUE THREAD

**Issue by avzis** [open-telemetry/semantic-conventions#717]
**What are you trying to achieve?**

According to the [db spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#call-level-attributes), the `db.statement` value can be sanitized, but it is not defined how to do so.

Currently, the sanitization is being dealt with differently in few places.
I suggest to add a uniform format that will describe how to do the sanitization.
(It will be best if this format will apply to all different DB's and syntaxes)

Different implementations examples:
- [JS mongo db](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts#L606) - implements the sanitization by replacing the information with question marks
- [Python pymongo](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-pymongo/src/opentelemetry/instrumentation/pymongo/__init__.py#L202) - implements the sanitization by deleting the information completely, and leaving the query method name only 
- [Python elasticsearch (WIP) ](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1598) - suggests to replace the information with a string that will explain that the data is sanitized

I suggest a few options to replace the value with:

- **Keep the method name, and add a sanitized text.** 
**for example:** `db.statement = "SELECT {query information is sanitized}"`
**advantages:** quite easy to implement, easy to keep consistent across libraries.
**dis-advantages:** will require to research whether all different libraries can handle this format effectively.

- **Simple text that will describe that the value is sanitized.**
**for example:** `db.statement = "query information is sanitized"`
**advantages:** easy to implement, easy to keep consistent across different libraries.
**dis-advantages:** doesn't supply basic information about the query that could be useful.

- **Replace the values with question marks.**
 **for example:** `db.statement = "SELECT ? FROM ?"`
 **advantages:** keeps more amount of information, while still not exposing sensitive or private data.
 **dis-advantages:** harder to implement, harder to keep consistent across libraries. 
 
 I would like to hear opinions about the suggested solutions, or hear different ideas.

**Additional context.**

open-telemetry/opentelemetry-specification#3104 - Issue regarding changing the recommendation to sanitize the information by default.
open-telemetry/semantic-conventions#708 - Issue about missing examples for sanitization in specs.

**Comment by trask** [comment]
possible language for SQL queries:

> replace all literal values with `?`

**Comment by trask** [comment]
should normalization be part of this or not? e.g.

> normalize `in (?, ?, ?, ?, ...)` to `in (?)`

or

> normalize `in (?, ?, ?, ?, ...)` to `in (_more10_50_)` to give an idea of number of items in the inlist

**Comment by maryliag** [comment]
> Keep the method name, and add a sanitized text.
for example: db.statement = "SELECT {query information is sanitized}"
advantages: quite easy to implement, easy to keep consistent across libraries.
dis-advantages: will require to research whether all different libraries can handle this format effectively.

I wouldn't say is necessarily easy, because how do you decide the "main" method on a statement that have multiple methods such as update and select. Or statements that start with `WITH`, how the method is decided.

> Replace the values with question marks.
for example: db.statement = "SELECT ? FROM ?"
advantages: keeps more amount of information, while still not exposing sensitive or private data.
dis-advantages: harder to implement, harder to keep consistent across libraries.

For this one I think is more helpful for the user but agree it will required a harder level to implement and keep consistency. For example, on CockroachDB the [replacements](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/adjust_constants.go) were something as follows:
placeholders: `$1`
strings: `'_'`
anything else: `_`

When there was `IN` clause, it would be [replaced](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/adjust_constants.go#L351-L367) by one of the values: `__more1_10__`, `__more10_100__`,  `_moreX__` (with X the between 100 and 1000, such as 100, 200, 300,...) or `__more1000_plus__`. That created a nice balance of separating groups that would use different plan executions, but at the same time keeping cardinality lower of different possible final strings, since the list can be quite big (I saw cases with 20k+ values in a list)

Another thing to consider on this option is level of sanitization, because is more common for the values to be hidden, but not the columns, so it would need options for sanitazing just the value or the value + columns.

**Comment by trask** [comment]
thoughts from SIG meeting:

* general statement for all dbs - replace all string and numeric literals with some placeholder (maybe `?`)

**Comment by trask** [comment]
from SIG meeting:

* don't sanitize placeholders themselves (e.g. https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11379)
