### ISSUE TITLE
Should `db.sql.table` include `db.name`?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#718]
Currently `db.sql.table` is defined as:

> The name of the primary table that the operation is acting upon, including the database name (if applicable). [1]

I'm not sure why it includes `db.name` since we have a separate attribute specifically for that, and could parse the `db.name` out from the full `db.sql.table` expression.

**Comment by jcocchi** [comment]
I agree it doesn't make sense to duplicate the database name in both the `db.name` and `db.sql.table` attributes. 

Many databases will have their own term for "table", in Cosmos DB it's called "container". Does it make sense to use a general term in the semantic convention or let each database have their own native terminology?

**Comment by Oberon00** [comment]
@trask You introduced this in https://github.com/open-telemetry/opentelemetry-specification/pull/1973/files#diff-38d5c918b32cb78e2489cc98d2157cbe5c3306fcbfe4aa6235d25f3468305eeaR373, if you are not sure why yourself, then it seems to have been a mistake when attempting to translate the cassandra-specific note about the keyspace. I agree that including the DB name does not make sense, probably this was unintentional?

**Comment by Oberon00** [comment]
This was changed in https://github.com/open-telemetry/opentelemetry-specification/pull/1973/files#diff-38d5c918b32cb78e2489cc98d2157cbe5c3306fcbfe4aa6235d25f3468305eeaR373

It used to say schema name, which imo makes sense for SQL as it would then be equivalent to saying that we want to have the fully qualified table name. But maybe we should just say that, i.e. instead of schema/db name, it should be the fully qualified table name?

**Comment by trask** [comment]
Resolved by #870 where `db.sql.table` was replaced by `db.collection.name`, which

> SHOULD match the value provided in the query and may be qualified with the schema and database name
