### ISSUE TITLE
HTTP Spans is getting closed when a child span created inside another thread

### ISSUE THREAD

**Issue by itsmykairos** [open-telemetry/semantic-conventions#752]
I am facing an issue with HTTP Spans, that is getting closed while creating a child span inside another thread using completable future. Span propagation is happening(since wrapped executor service with otel) and I can see the parent span inside other thread's method, but the moment we create a child span, parent span is ended and isRecording gives false. This is happening with HTTP Spans alone, Spans created with **@WithSpan** works fine, when I add it on top of method returns CompletableFuture. Please let me know if I'm missing something, This same code was working fine with opentracing.contrib.spring library.

Im using spring-boot 3 with otel-spring-boot-starter

**Comment by lmolkova** [comment]
@itsmykairos you probably want to open the issue in the [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation) or [opentelemetry-java-contrib repository](https://github.com/open-telemetry/opentelemetry-java-contrib). 

Please also provide the repro application and/or versions of agent and instrumentation libraries you're using, which HTTP client is used, version of that client (and possibly other information requested by the issue template on the corresponding repository).
If you happen to use sole older versions of otel agent or instrumentation library, please also try the latest version.


Since this issue is not related to semantic conventions, I'm going to close it.
