### ISSUE TITLE
[HTTP] Several questions about `server.address` and `server.socket.address`

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/semantic-conventions#85]
I'm currently implementing a prototype/POC of the new HTTP semconv in Java instrumentation, and I ran into some interesting differences when compared to the old version of the spec.

1. In the [old version of the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.20.0/specification/trace/semantic_conventions/http.md#common-attributes) the `net.sock.peer.name` and `net.sock.peer.port` were only collected when `net.sock.peer.addr` was present. That is not the case for the new attributes: `server.socket.port` can be collected when `server.socket.address` is absent. Is that intentional?

2. On the [HTTP server side](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions) `server.socket.address` and `server.socket.port` are marked as Opt-In. If the user happens to opt into collecting these, should the   "If different than `server.address` (`server.port`)" condition also apply here? (it applies both on the HTTP client side and in the general `server.*` semantics)

3. Similar to question 1.: should we set `server.socket.domain` if it's the same as `server.address`?

CC @trask @lmolkova

**Comment by lmolkova** [comment]
> 1. client

`server.socket.address` is recommended if different than `server.address` (same for ports). Feels like it's the same as what we had in the old spec (if direct peer info is available and different than logical peer, it should be populated. It should not be populated otherwise).

It seems theoretically possible to have  `server.socket.port` without `server.socket.address` (proxy on the same host as service, e.g. in test env):
- `server.address` : "1.2.3.4"
- `server.port`: 80
- `server.socket.port`:42 

> 2. server

Good question.

On the server side, `server.socket.address` and `server.socket.port` represent the services IP address and port.
I believe `server.socket.address` would almost never match `server.address` (usually service is behind proxy, load balancer, and client would use DNS name instead of IP). 
If user opts into the attribute, it feels, they believe this information is necessary and we should not drop it for any reason.

Same with port- likely local port is not the one client sent the request to and since user decided they need this attribute, no need to drop it. 

I.e. adding more requirements for opt-in attributes brings more complexity and confusion and is probably not necessary when users decided they need the info. 

> 3. `server.socket.domain`

I think you're right and what's missing in the new version is a recommendation for `server.socket.domain` to be populated only when it does not match `server.address`.
