### ISSUE TITLE
Remove `db.user`?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions#885]
It seems to overlap with #731.

I'm not sure that `db.user` is an important default database metric attribute, and so we could remove it for now, and capture database user on spans in the future under the `user.*` namespace once #731 is resolved.

**Comment by AlexanderWert** [comment]
Once #731 AND https://github.com/open-telemetry/build-tools/issues/240 are resolved, we could re-introduce the user fields under the `db` namespace (if needed).  

Similar to the conversation here https://github.com/open-telemetry/semantic-conventions/pull/564#discussion_r1549586908, I think we should avoid ambiguous `user.*` attributes that are not in a concrete context (i.e. parent namespace). As `user` is a very generic concept we should put it into a parent namespace whenever it is being used in a concrete context, to make clear what kind of user it is. Otherwise, if a signal has `user.*` fields it's not clear what kind of user it refers to (the OS user running the underlying process? the Web user that is authenticated with the service? The DB user? etc.). And, in fact a single signal could even have multiple different users associated. 

+1 on removing `db.user` attribute for now, and potentially introducing the `db.user.*` namespace later again with #731 and https://github.com/open-telemetry/build-tools/issues/240

**Comment by trask** [comment]
hi @jerry-shao! we definitely intend for there to be a replacement for capturing "database user", we're just not sure what the attribute name will be yet

**Comment by trask** [comment]
would you mind opening a new issue to track this, i.e. how to capture database user?

**Comment by jerry-shao** [comment]
Created a new issue to track this: https://github.com/open-telemetry/semantic-conventions/issues/1142
